
import { Party, Product, Transaction } from '../types';
import { formatNepaliDate } from './nepaliDateService';

declare const XLSX: any;

export const exportToExcel = (data: any[], fileName: string) => {
  if (typeof XLSX === 'undefined') {
    alert('Excel library not loaded. Please check your internet connection.');
    return;
  }
  
  // Create worksheet
  const ws = XLSX.utils.json_to_sheet(data);
  
  // Create workbook
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Sheet1");
  
  // Generate file
  XLSX.writeFile(wb, `${fileName}_${new Date().toISOString().split('T')[0]}.xlsx`);
};

export const printData = (title: string, columns: string[], rows: any[][]) => {
  const printWindow = window.open('', '_blank');
  if (!printWindow) return;

  const tableHeader = columns.map(c => `<th style="border:1px solid #e2e8f0; padding:12px 8px; text-align:left; background-color:#f8fafc; color:#475569; font-weight:600; font-size: 12px;">${c}</th>`).join('');
  
  const tableRows = rows.map((row, i) => {
    const bg = i % 2 === 0 ? '#ffffff' : '#fcfcfc';
    const cells = row.map(cell => `<td style="border:1px solid #e2e8f0; padding:8px; font-size: 12px; color:#334155;">${cell !== undefined && cell !== null ? cell : ''}</td>`).join('');
    return `<tr style="background-color:${bg}">${cells}</tr>`;
  }).join('');

  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>${title}</title>
        <style>
          @page { size: A4; margin: 20mm; }
          body { font-family: 'Inter', system-ui, sans-serif; padding: 20px; color: #1e293b; }
          h1 { text-align: center; color: #0f172a; font-size: 24px; margin-bottom: 5px; }
          .meta { text-align: center; color: #64748b; font-size: 12px; margin-bottom: 30px; }
          table { width: 100%; border-collapse: collapse; margin-top: 10px; }
          .footer { margin-top: 40px; text-align: center; font-size: 10px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 20px; }
        </style>
      </head>
      <body>
        <h1>${title}</h1>
        <div class="meta">Generated on: ${new Date().toLocaleString()}</div>
        <table>
          <thead>
            <tr>${tableHeader}</tr>
          </thead>
          <tbody>
            ${tableRows}
          </tbody>
        </table>
        <div class="footer">Generated by AA Pro Business Solutions</div>
        <script>
          window.onload = function() { window.print(); }
        </script>
      </body>
    </html>
  `;

  printWindow.document.write(html);
  printWindow.document.close();
};

// --- Data Transformers ---

export const transformProductsForExport = (products: Product[]) => {
  return products.map(p => ({
    'Item Name': p.name,
    'Category': p.category,
    'Type': p.type,
    'Stock': p.stock,
    'Unit': p.unit,
    'Purchase Price': p.purchasePrice,
    'Sale Price': p.salePrice,
    'Wholesale Price': p.wholesalePrice || 0
  }));
};

export const transformPartiesForExport = (parties: Party[]) => {
  return parties.map(p => ({
    'Name': p.name,
    'Type': p.type,
    'Phone': p.phone,
    'Balance': p.balance,
    'Status': p.balance > 0 ? 'Receivable' : (p.balance < 0 ? 'Payable' : 'Settled')
  }));
};

export const transformTransactionsForExport = (transactions: Transaction[]) => {
  return transactions.map(t => ({
    'Date': formatNepaliDate(t.date),
    'Voucher No': t.id,
    'Type': t.type,
    'Party': t.partyName,
    'Total Amount': t.totalAmount,
    'Paid Via': t.paymentMode || '-',
    'Remarks': t.notes || ''
  }));
};
